import React from 'react';
import { View, Text, ScrollView, TouchableOpacity } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

const Section = ({ title, children }) => (
  <View style={{ marginBottom: 16 }}>
    <Text style={{ fontSize: 16, fontWeight: '700', marginBottom: 8 }}>{title}</Text>
    <Text style={{ fontSize: 14, color: '#333', lineHeight: 20 }}>{children}</Text>
  </View>
);

const List = ({ items = [] }) => (
  <View style={{ marginTop: 6 }}>
    {items.map((item, idx) => (
      <View key={idx} style={{ flexDirection: 'row', marginBottom: 6 }}>
        <Text style={{ marginRight: 6 }}>•</Text>
        <Text style={{ flex: 1, fontSize: 14, color: '#333', lineHeight: 20 }}>{item}</Text>
      </View>
    ))}
  </View>
);

const PrivacyPolicy = ({ navigation }) => {
  return (
    <View style={{ flex: 1, backgroundColor: '#fff' }}>
      <View style={{ backgroundColor: '#47D6FF', justifyContent: 'center', alignItems: 'center', width: '100%', height: 60, flexDirection: 'row' }}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={{ position: 'absolute', left: 20 }}>
          <Ionicons name="arrow-back" size={24} color="#fff" />
        </TouchableOpacity>
        <Text style={{ fontSize: 18, fontWeight: 'bold', color: '#fff' }}>Privacy Policy</Text>
      </View>

      <ScrollView contentContainerStyle={{ padding: 20 }}>
        <Text style={{ fontSize: 12, color: '#666', marginBottom: 16 }}>Last updated: {new Date().toLocaleDateString()}</Text>

        <Section title="Introduction">
          Rent-To-Build protects your privacy. This policy explains what data we collect, how we use it, and your choices. By using the app, you agree to this policy.
        </Section>

        <Section title="Data We Collect">
          We collect data you provide and data generated by your use of the app.
          <List items={[
            'Account info: name, email, phone, CNIC, profile image',
            'Ad details: machinery info, images, city/location (you manually enter it)',
            'Messages: chat content for support and machinery inquiries',
            'Settings: privacy preferences like Show Location',
            'Device info: basic diagnostics and logs to keep the app reliable'
          ]} />
        </Section>

        <Section title="Images and Storage">
          Images you upload are stored via Cloudinary. We only upload photos you explicitly select. We do not automatically scan your gallery.
        </Section>

        <Section title="How We Use Data">
          <List items={[
            'Account and authentication: sign up / login, keep your session active',
            'Ads: create, edit, approve, and display your machinery listings',
            'Media: store and show images you upload for ads and profile',
            'Messaging: deliver and store chat messages for support and inquiries',
            'Location display: show city/location on ads only if Show Location is enabled by you',
            'Notifications: send critical updates like chat replies and status changes',
            'Safety: detect abuse, prevent fraud, and comply with legal requests'
          ]} />
        </Section>

        <Section title="Your Controls">
          <List items={[
            'Show Location: turn on/off location visibility on your ads and owner profile',
            'Edit Profile: change name, phone, CNIC, and profile photo',
            'Manage Ads: edit or delete your listings any time',
            'Data Requests: contact support to export or delete your account/data'
          ]} />
        </Section>

        <Section title="Data Sharing">
          <List items={[
            'Firebase Auth: account sign-in and session management',
            'Firebase Firestore: store user profiles, ads, chats, and settings',
            'Cloudinary: host images you choose to upload (ads/profile images)',
            'Law Enforcement: if legally required or to protect rights, users, or property'
          ]} />
        </Section>

        <Section title="Security">
          We use industry-standard protections through our providers (Firebase, Cloudinary). No system is 100% secure, but we work to safeguard your data.
        </Section>

        <Section title="Children">
          The service is not intended for children under 13. If we learn a child provided data, we will delete it.
        </Section>

        <Section title="Retention">
          We retain data for as long as needed to provide the service or as required by law. You can request deletion of your account/data.
        </Section>

        <Section title="Changes">
          We may update this policy. Material changes will be reflected in-app with an updated date.
        </Section>

        <Section title="Contact">
          For privacy questions or requests, contact: support@rent-to-build.example
        </Section>
      </ScrollView>
    </View>
  );
};

export default PrivacyPolicy;


